// EmailJS Setup Instructions
console.log("=== EmailJS Setup Instructions ===")
console.log("")
console.log("1. Go to https://www.emailjs.com/ and create a free account")
console.log("2. Create a new email service (Gmail, Outlook, etc.)")
console.log("3. Create an email template with these variables:")
console.log("   - {{from_name}} - sender's name")
console.log("   - {{from_email}} - sender's email")
console.log("   - {{subject}} - email subject")
console.log("   - {{message}} - email message")
console.log("   - {{to_email}} - your email (sagarmaddi1402@gmail.com)")
console.log("")
console.log("4. Get your credentials:")
console.log("   - Public Key (User ID)")
console.log("   - Service ID")
console.log("   - Template ID")
console.log("")
console.log("5. Replace these values in Contact.js:")
console.log("   - YOUR_PUBLIC_KEY with your Public Key")
console.log("   - YOUR_SERVICE_ID with your Service ID")
console.log("   - YOUR_TEMPLATE_ID with your Template ID")
console.log("")
console.log("Example template content:")
console.log("Subject: New message from {{from_name}}")
console.log("")
console.log("Body:")
console.log("Name: {{from_name}}")
console.log("Email: {{from_email}}")
console.log("Subject: {{subject}}")
console.log("")
console.log("Message:")
console.log("{{message}}")
console.log("")
console.log("=== Setup Complete! ===")
